"""Edit Task and Activity routes, add lazy_load for param project, add to schema params

Revision ID: 9afd57f201b5
Revises: faa9dae0cd85
Create Date: 2025-03-04 14:49:52.726833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afd57f201b5'
down_revision: Union[str, None] = 'faa9dae0cd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
