"""Add due_time to tasks and projects

Revision ID: faa9dae0cd85
Revises: 398f37a1964d
Create Date: 2025-03-04 09:38:28.142427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa9dae0cd85'
down_revision: Union[str, None] = '398f37a1964d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('projects', 'due_date')
    # ### end Alembic commands ###
